// Auto-generated by add_indices.py
import Coverage from "./Coverage";
import ExtendedPlantPhoto from "./ExtendedPlantPhoto";
import HistoryTable from "./HistoryTable";
import IndexTable from "./IndexTable";
import PlantNetResult from "./PlantNetResult";
import PlantPhoto from "./PlantPhoto";
import Species from "./Species";
import Statistics from "./Statistics";

export {
  Coverage,
  ExtendedPlantPhoto,
  HistoryTable,
  IndexTable,
  PlantNetResult,
  PlantPhoto,
  Species,
  Statistics,
};
